### ISSUE TITLE
Add unit tests for wordLoader

### ISSUE THREAD

**Issue by sesamechicken** [sesamechicken/spelling-buddy#9]
Add unit tests for wordLoader

**Comment by jmk-198xtsuga** [comment]
Between this and #10 I think one was meant to be fileLoader.  I vote this issue gets to test fileLoader, and I'll be glad to see what I can add!

**Comment by sesamechicken** [comment]
So fileLoader is a component that I've been meaning to implement, but haven't had time. The idea is that a user has a static list of words somewhere (Google Drive, Dropbox, etc) and fileLoader brings those in and sets them as the list.

For now, wordLoader is how words get loaded (manually), and it definitely needs tests around it.

**Comment by sesamechicken** [comment]
https://github.com/sesamechicken/spelling-buddy/pull/14 closes this one! :)
